more work on FZF options

diff --git a/default/zshrc b/default/zshrc
--- a/default/zshrc
+++ b/default/zshrc
@@ -130,9 +130,12 @@ export BAT_PAGER="less -R"
 # FZF configuration zsh
 # --------------------------------------------------------------------
 # original export FZF_DEFAULT_COMMAND="rg --files --hidden --no-ignore-dot --follow"
-export FZF_DEFAULT_COMMAND='fd --type f --color=never --hidden'
+export FZF_DEFAULT_COMMAND="fd --type f --color=never --hidden --exclude '.git' --exclude '.cache'"
 export FZF_DEFAULT_OPTS=" \
     --no-height \
+    --info=inline \
+    --layout=reverse \
+    --preview-window=:hidden \
     --multi \
     --cycle \
     --color=bg+:#343d46,gutter:-1,pointer:#ff3c3c,info:#0dbc79,hl:#0dbc79,hl+:#23d18b \
@@ -144,8 +147,28 @@ export FZF_DEFAULT_OPTS=" \
     --bind 'ctrl-v:execute(code {+})'"
 
 export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
-export FZF_CTRL_T_OPTS="--preview '[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always {} || cat {}) 2>/dev/null | head -300'"
-# export FZF_CTRL_T_OPTS="--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'"
+
+# The --preview option takes a command that is executed for the current line
+# and its output is displayed on the preview window. First, we check if the
+# string is a file, and if so, we try to open it with bat, if that fails, we
+# fall back to cat:
+#
+#     ([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {}))
+#
+# If the string is not a file, we check if it is a directory. If so, we try to
+# open it with tree, if that fails, we fall back to less:
+#
+#     ([[ -d {} ]] && (tree -C {} | less))
+#
+# If it’s not a file or directory, our last resource is to echo it:
+#
+#     echo {}
+#
+# Finally, we redirect any errors to /dev/null and return the first 200 lines:
+#
+#     2> /dev/null | head -200
+export FZF_CTRL_T_OPTS="--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'"
+#export FZF_CTRL_T_OPTS="--preview '[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || (bat --style=numbers --color=always {} || cat {}) 2>/dev/null | head -300'"
 
 export FZF_ALT_C_COMMAND='fd --type d . --color=never --hidden'
 export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -50'"
@@ -153,6 +176,9 @@ export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -50'"
 # File generated by the command
 #     $(brew --prefix)/opt/fzf/install
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
+
+# I use iterm2 and there ALT-C is processed as ç
+bindkey "ç" fzf-cd-widget
 
 # --------------------------------------------------------------------
 # Completion
